version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
      - image: mcr.microsoft.com/dotnet/sdk:5.0
    steps:
      - checkout
      - run:
          name: Restore solution
          command: dotnet restore DotnetCore-Samples.sln
      - run:
          name: Build solution
          command: dotnet build DotnetCore-Samples.sln
      - run:
          name: Run tests 
          command: dotnet test --no-build --logger "trx;LogFileName=../../../xunit-output.xml" DotnetCore/NUnitTestSample
