version: 2
jobs:
  build:
    docker:
      - image: microsoft/aspnetcore-build:latest
    steps:
      - checkout
      - run:
          name: Restore solution
          command: dotnet restore DotnetCore-Samples.sln
      - run:
          name: Build solution
          command: dotnet build DotnetCore-Samples.sln
      - run:
          name: Run tests 
          command: dotnet test --no-build --logger "trx;LogFileName=../../../xunit-output.xml" DotnetCore/
